#!/bin/bash

read -p "Будь ласка, введіть назву каталогу: " dir_name

if [ -d "$dir_name" ]; then
  echo "Помилка: каталог з назвою $dir_name вже існує."
  exit 1
fi

if [[ ! $dir_name =~ .*[0-9][0-9].* || ${#dir_name} -lt 4 ]]; then
  echo "Помилка: ім'я каталогу повинно мати 2 і більше цифри підряд та мати довжину не менше 4 символів."
  exit 1
fi

mkdir "$dir_name"
echo "Каталог $dir_name був успішно створений."
